# after initial EDA, lets train xgboost model with following set of features

feature set

Course Domain
Course Type
Short Promotion
Public Holiday

In [88]:
# import necessary packages
import pandas as pd
import matplotlib.pyplot as plt
import itertools
import datetime
import seaborn as sns
import numpy as np
from sklearn.metrics import *
import xgboost as xgb
import operator

%matplotlib inline
sns.set()

In [2]:
# import datasets
st = datetime.datetime.now()
train_data = pd.read_csv("../data/train.csv")
test_data = pd.read_csv("../data/test_QkPvNLx.csv")
print("total time req to load data ",datetime.datetime.now() - st)

total time req to load data  0:00:01.676353

In [3]:
input_features = ["Course_Domain","Course_Type","Short_Promotion","Public_Holiday"]
target = ["Sales"]
categorical_features = ["Course_Domain","Course_Type"]
input_cols = ["Course_Domain","Course_Type","Short_Promotion","Public_Holiday","Sales"]

## One Hot Categorical Features

### combine training and testing data before one hot encoding

In [4]:
train_data["Flag"] = "train"
test_data["Flag"] = "test"
train_test_data = pd.concat([train_data,
                            test_data])
train_test_data.shape

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  after removing the cwd from sys.path.

(548087, 12)

In [5]:
train_data.shape[0]+test_data.shape[0],train_test_data.shape

(548087, (548087, 12))

In [6]:
train_test_data.columns

Index(['Competition_Metric', 'Course_Domain', 'Course_ID', 'Course_Type',
       'Day_No', 'Flag', 'ID', 'Long_Promotion', 'Public_Holiday', 'Sales',
       'Short_Promotion', 'User_Traffic'],
      dtype='object')

In [7]:
train_data.isnull().sum()

ID                       0
Day_No                   0
Course_ID                0
Course_Domain            0
Course_Type              0
Short_Promotion          0
Public_Holiday           0
Long_Promotion           0
User_Traffic             0
Competition_Metric    1764
Sales                    0
Flag                     0
dtype: int64

In [8]:
test_data.isnull().sum()

ID                      0
Day_No                  0
Course_ID               0
Course_Domain           0
Course_Type             0
Short_Promotion         0
Public_Holiday          0
Long_Promotion          0
Competition_Metric    120
Flag                    0
dtype: int64

In [9]:
train_test_data.isnull().sum()

Competition_Metric     1884
Course_Domain             0
Course_ID                 0
Course_Type               0
Day_No                    0
Flag                      0
ID                        0
Long_Promotion            0
Public_Holiday            0
Sales                 36000
Short_Promotion           0
User_Traffic          36000
dtype: int64

In [10]:
st = datetime.datetime.now()
one_hot_train_test_data = pd.get_dummies(train_test_data,columns=categorical_features)
print("Time taken for One hot encoding ",datetime.datetime.now() - st)
one_hot_train_test_data.shape

Time taken for One hot encoding  0:00:00.162106

(548087, 17)

In [11]:
one_hot_train_test_data

,Competition_Metric,Course_ID,Day_No,Flag,ID,Long_Promotion,Public_Holiday,Sales,Short_Promotion,User_Traffic,Course_Domain_Business,Course_Domain_Development,Course_Domain_Finance & Accounting,Course_Domain_Software Marketing,Course_Type_Course,Course_Type_Degree,Course_Type_Program
0,0.007,1,1,train,1,1,1,81.0,0,11004.0,0,1,0,0,1,0,0
1,0.007,1,2,train,2,1,0,79.0,0,13650.0,0,1,0,0,1,0,0
2,0.007,1,3,train,3,1,0,75.0,0,11655.0,0,1,0,0,1,0,0
3,0.007,1,4,train,4,1,0,80.0,0,12054.0,0,1,0,0,1,0,0
4,0.007,1,5,train,5,1,0,41.0,0,6804.0,0,1,0,0,1,0,0
5,0.007,1,6,train,6,1,0,62.0,0,10395.0,0,1,0,0,1,0,0
6,0.007,1,7,train,7,1,0,122.0,1,16023.0,0,1,0,0,1,0,0
7,0.007,1,8,train,8,1,0,114.0,1,14385.0,0,1,0,0,1,0,0
8,0.007,1,9,train,9,1,0,121.0,1,16485.0,0,1,0,0,1,0,0
9,0.007,1,10,train,10,1,0,100.0,1,13377.0,0,1,0,0,1,0,0
10,0.007,1,11,train,11,1,0,86.0,1,11319.0,0,1,0,0,1,0,0
11,0.007,1,12,train,12,1,0,47.0,0,7077.0,0,1,0,0,1,0,0
12,0.007,1,13,train,13,1,0,85.0,0,11802.0,0,1,0,0,1,0,0
13,0.007,1,14,train,14,1,0,72.0,0,11130.0,0,1,0,0,1,0,0
14,0.007,1,15,train,15,1,0,74.0,0,10773.0,0,1,0,0,1,0,0
15,0.007,1,16,train,16,1,0,76.0,0,12411.0,0,1,0,0,1,0,0
16,0.007,1,17,train,17,1,0,53.0,0,8463.0,0,1,0,0,1,0,0
17,0.007,1,18,train,18,1,0,61.0,0,9114.0,0,1,0,0,1,0,0
18,0.007,1,19,train,19,1,0,42.0,0,6363.0,0,1,0,0,1,0,0
19,0.007,1,20,train,20,1,0,51.0,0,8547.0,0,1,0,0,1,0,0
20,0.007,1,21,train,21,1,0,114.0,1,13902.0,0,1,0,0,1,0,0
21,0.007,1,22,train,22,1,0,104.0,1,13776.0,0,1,0,0,1,0,0
22,0.007,1,23,train,23,1,0,107.0,1,14490.0,0,1,0,0,1,0,0
23,0.007,1,24,train,24,1,0,92.0,1,12222.0,0,1,0,0,1,0,0
24,0.007,1,25,train,25,1,0,82.0,1,10962.0,0,1,0,0,1,0,0
25,0.007,1,26,train,26,1,0,39.0,0,6363.0,0,1,0,0,1,0,0
26,0.007,1,27,train,27,1,0,80.0,0,11256.0,0,1,0,0,1,0,0
27,0.007,1,28,train,28,1,0,63.0,0,10248.0,0,1,0,0,1,0,0
28,0.007,1,29,train,29,1,0,61.0,0,9996.0,0,1,0,0,1,0,0
29,0.007,1,30,train,30,1,0,80.0,0,12768.0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35970,0.070,600,913,test,548058,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35971,0.070,600,914,test,548059,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35972,0.070,600,915,test,548060,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35973,0.070,600,916,test,548061,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35974,0.070,600,917,test,548062,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35975,0.070,600,918,test,548063,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35976,0.070,600,919,test,548064,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35977,0.070,600,920,test,548065,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35978,0.070,600,921,test,548066,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35979,0.070,600,922,test,548067,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35980,0.070,600,923,test,548068,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35981,0.070,600,924,test,548069,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35982,0.070,600,925,test,548070,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35983,0.070,600,926,test,548071,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35984,0.070,600,927,test,548072,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35985,0.070,600,928,test,548073,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35986,0.070,600,929,test,548074,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35987,0.070,600,930,test,548075,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35988,0.070,600,931,test,548076,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35989,0.070,600,932,test,548077,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35990,0.070,600,933,test,548078,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35991,0.070,600,934,test,548079,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35992,0.070,600,935,test,548080,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35993,0.070,600,936,test,548081,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35994,0.070,600,937,test,548082,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35995,0.070,600,938,test,548083,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35996,0.070,600,939,test,548084,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35997,0.070,600,940,test,548085,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35998,0.070,600,941,test,548086,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35999,0.070,600,942,test,548087,1,0,NaN,1,NaN,0,0,0,1,0,0,1

In [12]:
# separate one hot train test data

one_hot_train_data = one_hot_train_test_data[one_hot_train_test_data.Flag=="train"]
one_hot_test_data = one_hot_train_test_data[one_hot_train_test_data.Flag=="test"]

one_hot_train_data.shape,train_data.shape,one_hot_test_data.shape,test_data.shape

((512087, 17), (512087, 12), (36000, 17), (36000, 10))

In [13]:
input_features

['Course_Domain', 'Course_Type', 'Short_Promotion', 'Public_Holiday']

In [14]:
cols_to_exclude = ['Competition_Metric', 'Course_ID', 'Day_No', 'Flag', 'ID','Long_Promotion', 'Sales','User_Traffic']

In [123]:
cols_to_exclude

['Competition_Metric',
 'Course_ID',
 'Day_No',
 'Flag',
 'ID',
 'Long_Promotion',
 'Sales',
 'User_Traffic']

## Model Preparation

In [16]:
# convert train data to the xgboost train object

xgb_train_data = xgb.DMatrix(one_hot_train_data[one_hot_train_data.columns.difference(cols_to_exclude)],one_hot_train_data[target])
xgb_test_data = xgb.DMatrix(one_hot_test_data[one_hot_test_data.columns.difference(cols_to_exclude)])

In [17]:
# initial training params
train_params = {"objective" : "reg:linear", "eval_metric" : "rmse"}

## train model

In [18]:

xgb_model = xgb.train(params=train_params,dtrain=xgb_train_data)

[11:40:32] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.

## check feature importance by model

In [34]:
sorted(xgb_model.get_fscore().items(),key=operator.itemgetter(1),reverse=True)

[('Course_Domain_Business', 60),
 ('Course_Domain_Development', 58),
 ('Course_Domain_Finance & Accounting', 51),
 ('Public_Holiday', 39),
 ('Course_Type_Course', 35),
 ('Course_Domain_Software Marketing', 32),
 ('Short_Promotion', 10)]

## evaluate model on training data

In [35]:
np.sqrt(mean_squared_error(one_hot_train_data[target],
                           xgb_model.predict(xgb.DMatrix(one_hot_train_data[one_hot_train_data.columns.difference(cols_to_exclude)])))
       )

48.95879660720635

In [36]:
one_hot_train_data.Sales.describe()

count    512087.000000
mean        120.826924
std          54.355258
min           0.000000
25%          84.000000
50%         111.000000
75%         146.000000
max         682.000000
Name: Sales, dtype: float64

In [37]:
one_hot_test_data

,Competition_Metric,Course_ID,Day_No,Flag,ID,Long_Promotion,Public_Holiday,Sales,Short_Promotion,User_Traffic,Course_Domain_Business,Course_Domain_Development,Course_Domain_Finance & Accounting,Course_Domain_Software Marketing,Course_Type_Course,Course_Type_Degree,Course_Type_Program
0,0.007,1,883,test,883,1,0,NaN,1,NaN,0,1,0,0,1,0,0
1,0.007,1,884,test,884,1,0,NaN,1,NaN,0,1,0,0,1,0,0
2,0.007,1,885,test,885,1,0,NaN,1,NaN,0,1,0,0,1,0,0
3,0.007,1,886,test,886,1,0,NaN,1,NaN,0,1,0,0,1,0,0
4,0.007,1,887,test,887,1,0,NaN,0,NaN,0,1,0,0,1,0,0
5,0.007,1,888,test,888,1,0,NaN,0,NaN,0,1,0,0,1,0,0
6,0.007,1,889,test,889,1,0,NaN,0,NaN,0,1,0,0,1,0,0
7,0.007,1,890,test,890,1,0,NaN,0,NaN,0,1,0,0,1,0,0
8,0.007,1,891,test,891,1,0,NaN,0,NaN,0,1,0,0,1,0,0
9,0.007,1,892,test,892,1,0,NaN,0,NaN,0,1,0,0,1,0,0
10,0.007,1,893,test,893,1,0,NaN,0,NaN,0,1,0,0,1,0,0
11,0.007,1,894,test,894,1,0,NaN,0,NaN,0,1,0,0,1,0,0
12,0.007,1,895,test,895,1,0,NaN,0,NaN,0,1,0,0,1,0,0
13,0.007,1,896,test,896,1,0,NaN,1,NaN,0,1,0,0,1,0,0
14,0.007,1,897,test,897,1,0,NaN,1,NaN,0,1,0,0,1,0,0
15,0.007,1,898,test,898,1,0,NaN,1,NaN,0,1,0,0,1,0,0
16,0.007,1,899,test,899,1,0,NaN,1,NaN,0,1,0,0,1,0,0
17,0.007,1,900,test,900,1,0,NaN,1,NaN,0,1,0,0,1,0,0
18,0.007,1,901,test,901,1,0,NaN,0,NaN,0,1,0,0,1,0,0
19,0.007,1,902,test,902,1,0,NaN,0,NaN,0,1,0,0,1,0,0
20,0.007,1,903,test,903,1,0,NaN,0,NaN,0,1,0,0,1,0,0
21,0.007,1,904,test,904,1,0,NaN,0,NaN,0,1,0,0,1,0,0
22,0.007,1,905,test,905,1,0,NaN,0,NaN,0,1,0,0,1,0,0
23,0.007,1,906,test,906,1,0,NaN,0,NaN,0,1,0,0,1,0,0
24,0.007,1,907,test,907,1,0,NaN,0,NaN,0,1,0,0,1,0,0
25,0.007,1,908,test,908,1,0,NaN,0,NaN,0,1,0,0,1,0,0
26,0.007,1,909,test,909,1,0,NaN,0,NaN,0,1,0,0,1,0,0
27,0.007,1,910,test,910,1,0,NaN,1,NaN,0,1,0,0,1,0,0
28,0.007,1,911,test,911,1,0,NaN,1,NaN,0,1,0,0,1,0,0
29,0.007,1,912,test,912,1,0,NaN,1,NaN,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35970,0.070,600,913,test,548058,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35971,0.070,600,914,test,548059,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35972,0.070,600,915,test,548060,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35973,0.070,600,916,test,548061,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35974,0.070,600,917,test,548062,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35975,0.070,600,918,test,548063,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35976,0.070,600,919,test,548064,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35977,0.070,600,920,test,548065,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35978,0.070,600,921,test,548066,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35979,0.070,600,922,test,548067,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35980,0.070,600,923,test,548068,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35981,0.070,600,924,test,548069,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35982,0.070,600,925,test,548070,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35983,0.070,600,926,test,548071,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35984,0.070,600,927,test,548072,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35985,0.070,600,928,test,548073,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35986,0.070,600,929,test,548074,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35987,0.070,600,930,test,548075,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35988,0.070,600,931,test,548076,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35989,0.070,600,932,test,548077,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35990,0.070,600,933,test,548078,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35991,0.070,600,934,test,548079,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35992,0.070,600,935,test,548080,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35993,0.070,600,936,test,548081,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35994,0.070,600,937,test,548082,1,0,NaN,0,NaN,0,0,0,1,0,0,1
35995,0.070,600,938,test,548083,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35996,0.070,600,939,test,548084,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35997,0.070,600,940,test,548085,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35998,0.070,600,941,test,548086,1,0,NaN,1,NaN,0,0,0,1,0,0,1
35999,0.070,600,942,test,548087,1,0,NaN,1,NaN,0,0,0,1,0,0,1

In [38]:
test_predictions  = xgb_model.predict(xgb_test_data)
test_predictions

array([135.06668, 135.06668, 135.06668, ..., 142.7821 , 142.7821 ,
       142.7821 ], dtype=float32)

In [39]:
one_hot_test_data["Sales"] = test_predictions

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [40]:
one_hot_test_data.isnull().sum()

Competition_Metric                      120
Course_ID                                 0
Day_No                                    0
Flag                                      0
ID                                        0
Long_Promotion                            0
Public_Holiday                            0
Sales                                     0
Short_Promotion                           0
User_Traffic                          36000
Course_Domain_Business                    0
Course_Domain_Development                 0
Course_Domain_Finance & Accounting        0
Course_Domain_Software Marketing          0
Course_Type_Course                        0
Course_Type_Degree                        0
Course_Type_Program                       0
dtype: int64

In [41]:
test_submission = one_hot_test_data[["ID","Sales"]]
test_submission

           ID       Sales
0         883  135.066681
1         884  135.066681
2         885  135.066681
3         886  135.066681
4         887   93.063187
5         888   93.063187
6         889   93.063187
7         890   93.063187
8         891   93.063187
9         892   93.063187
10        893   93.063187
11        894   93.063187
12        895   93.063187
13        896  135.066681
14        897  135.066681
15        898  135.066681
16        899  135.066681
17        900  135.066681
18        901   93.063187
19        902   93.063187
20        903   93.063187
21        904   93.063187
22        905   93.063187
23        906   93.063187
24        907   93.063187
25        908   93.063187
26        909   93.063187
27        910  135.066681
28        911  135.066681
29        912  135.066681
...       ...         ...
35970  548058  142.782104
35971  548059  142.782104
35972  548060  106.117271
35973  548061  106.117271
35974  548062  106.117271
35975  548063  106.117271
35976  548064  106.117271
35977  548065  106.117271
35978  548066  106.117271
35979  548067  106.117271
35980  548068  106.117271
35981  548069  142.782104
35982  548070  142.782104
35983  548071  142.782104
35984  548072  142.782104
35985  548073  142.782104
35986  548074  106.117271
35987  548075  106.117271
35988  548076  106.117271
35989  548077  106.117271
35990  548078  106.117271
35991  548079  106.117271
35992  548080  106.117271
35993  548081  106.117271
35994  548082  106.117271
35995  548083  142.782104
35996  548084  142.782104
35997  548085  142.782104
35998  548086  142.782104
35999  548087  142.782104

[36000 rows x 2 columns]

In [42]:
test_submission["Sales"] = round(test_submission["Sales"])
test_submission

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

           ID  Sales
0         883  135.0
1         884  135.0
2         885  135.0
3         886  135.0
4         887   93.0
5         888   93.0
6         889   93.0
7         890   93.0
8         891   93.0
9         892   93.0
10        893   93.0
11        894   93.0
12        895   93.0
13        896  135.0
14        897  135.0
15        898  135.0
16        899  135.0
17        900  135.0
18        901   93.0
19        902   93.0
20        903   93.0
21        904   93.0
22        905   93.0
23        906   93.0
24        907   93.0
25        908   93.0
26        909   93.0
27        910  135.0
28        911  135.0
29        912  135.0
...       ...    ...
35970  548058  143.0
35971  548059  143.0
35972  548060  106.0
35973  548061  106.0
35974  548062  106.0
35975  548063  106.0
35976  548064  106.0
35977  548065  106.0
35978  548066  106.0
35979  548067  106.0
35980  548068  106.0
35981  548069  143.0
35982  548070  143.0
35983  548071  143.0
35984  548072  143.0
35985  548073  143.0
35986  548074  106.0
35987  548075  106.0
35988  548076  106.0
35989  548077  106.0
35990  548078  106.0
35991  548079  106.0
35992  548080  106.0
35993  548081  106.0
35994  548082  106.0
35995  548083  143.0
35996  548084  143.0
35997  548085  143.0
35998  548086  143.0
35999  548087  143.0

[36000 rows x 2 columns]

In [43]:
test_submission.to_csv("../data/test_predictions.csv",
                      header=True,
                      index=False)

In [79]:
input_features

['Course_Domain', 'Course_Type', 'Short_Promotion', 'Public_Holiday']

## lets use feature combinations and retrain model

## experiment 1

### train model by individual feature and check rmse on training data itself

In [85]:
# initial training params
train_params = {"objective" : "reg:linear", "eval_metric" : "rmse"}

for feature in input_features:
    print("\ninput feature for training ",feature)
#     model preparation
    # convert train data to the xgboost train object

    xgb_train_data = xgb.DMatrix(one_hot_train_data.loc[:,one_hot_train_data.columns.str.contains(feature)],
                                one_hot_train_data.loc[:,one_hot_train_data.columns.str.contains(target[0])])
    xgb_test_data = xgb.DMatrix(one_hot_test_data.loc[:,one_hot_test_data.columns.str.contains(feature)])
    
    xgb_model = xgb.train(params=train_params,dtrain=xgb_train_data)
    print("feature importance ", sorted(xgb_model.get_fscore().items(),key=operator.itemgetter(1),reverse=True))
    
    print("Training RMSE ",np.sqrt(mean_squared_error(one_hot_train_data.loc[:,one_hot_train_data.columns.str.contains(target[0])],
                           xgb_model.predict(xgb.DMatrix(one_hot_train_data.loc[:,one_hot_train_data.columns.str.contains(feature)]
                                                        )
                                            )
                                                     )
                                  )
       )

input feature for training  Course_Domain
[12:19:07] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 10), ('Course_Domain_Finance & Accounting', 10), ('Course_Domain_Development', 10)]
Training RMSE  54.08234851429263

input feature for training  Course_Type
[12:19:08] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 10), ('Course_Type_Degree', 10)]
Training RMSE  53.82835580168691

input feature for training  Short_Promotion
[12:19:10] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 10)]
Training RMSE  50.66330095887269

input feature for training  Public_Holiday
[12:19:10] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 10)]
Training RMSE  53.96477785701674

## experiment 2

### taken feature combination of 2

In [96]:
list(itertools.combinations(input_features,2))

[('Course_Domain', 'Course_Type'),
 ('Course_Domain', 'Short_Promotion'),
 ('Course_Domain', 'Public_Holiday'),
 ('Course_Type', 'Short_Promotion'),
 ('Course_Type', 'Public_Holiday'),
 ('Short_Promotion', 'Public_Holiday')]

In [122]:
# initial training params
train_params = {"objective" : "reg:linear", "eval_metric" : "rmse"}

for feature in list(itertools.combinations(input_features,2)):
    print("\ninput feature for training ",feature)
#     model preparation
    # convert train data to the xgboost train object

    xgb_train_data = xgb.DMatrix(one_hot_train_data.loc[:,(one_hot_train_data.columns.str.contains(feature[1]))|(one_hot_train_data.columns.str.contains(feature[0])) ],
                                one_hot_train_data.loc[:,one_hot_train_data.columns.str.contains(target[0])])
    xgb_test_data = xgb.DMatrix(one_hot_test_data.loc[:,(one_hot_test_data.columns.str.contains(feature[0]))|one_hot_test_data.columns.str.contains(feature[1])])
    
    xgb_model = xgb.train(params=train_params,dtrain=xgb_train_data)
    print("feature importance ", sorted(xgb_model.get_fscore().items(),key=operator.itemgetter(1),reverse=True))
    
    print("** Training RMSE ",np.sqrt(mean_squared_error(one_hot_train_data.loc[:,one_hot_train_data.columns.str.contains(target[0])],
                           xgb_model.predict(xgb.DMatrix(one_hot_train_data.loc[:,(one_hot_train_data.columns.str.contains(feature[1]))|(one_hot_train_data.columns.str.contains(feature[0])) ]
                                                        )
                                            )
                                                     )
                                  )
       )
    
    test_predictions  = xgb_model.predict(xgb_test_data)
    one_hot_test_data["Sales"] = test_predictions
    test_submission = one_hot_test_data[["ID","Sales"]]
    test_submission["Sales"] = round(test_submission["Sales"])
    test_submission.to_csv("../data/test_predictions"+"_with_feature_combinations_"+str(feature)+".csv",
                      header=True,
                      index=False)

input feature for training  ('Course_Domain', 'Course_Type')
[12:56:35] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 20), ('Course_Domain_Development', 20), ('Course_Type_Course', 10), ('Course_Domain_Software Marketing', 10), ('Course_Domain_Finance & Accounting', 10)]
** Training RMSE  53.382119958923816

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

input feature for training  ('Course_Domain', 'Short_Promotion')
[12:56:37] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 20), ('Course_Domain_Development', 15), ('Short_Promotion', 10), ('Course_Domain_Finance & Accounting', 10), ('Course_Domain_Software Marketing', 10)]
** Training RMSE  50.23942168680896

input feature for training  ('Course_Domain', 'Public_Holiday')
[12:56:39] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 20), ('Course_Domain_Finance & Accounting', 20), ('Course_Domain_Development', 20), ('Public_Holiday', 10)]
** Training RMSE  53.57005446678647

input feature for training  ('Course_Type', 'Short_Promotion')
[12:56:41] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 20), ('Course_Type_Degree', 20), ('Short_Promotion', 10)]
** Training RMSE  49.9787525775562

input feature for training  ('Course_Type', 'Public_Holiday')
[12:56:43] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 20), ('Course_Type_Degree', 20), ('Course_Type_Course', 10)]
** Training RMSE  53.32147688883888

input feature for training  ('Short_Promotion', 'Public_Holiday')
[12:56:44] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 20), ('Short_Promotion', 10)]
** Training RMSE  50.172487532618675

## experiment 3

### taken feature combination of 3

In [116]:
list(itertools.combinations(input_features,3))

[('Course_Domain', 'Course_Type', 'Short_Promotion'),
 ('Course_Domain', 'Course_Type', 'Public_Holiday'),
 ('Course_Domain', 'Short_Promotion', 'Public_Holiday'),
 ('Course_Type', 'Short_Promotion', 'Public_Holiday')]

In [121]:
# initial training params
train_params = {"objective" : "reg:linear", "eval_metric" : "rmse"}

for feature in list(itertools.combinations(input_features,3)):
    print("\ninput feature for training ",feature)
#     model preparation
    # convert train data to the xgboost train object

    xgb_train_data = xgb.DMatrix(one_hot_train_data.loc[:,(one_hot_train_data.columns.str.contains(feature[0]+"|"+feature[1]+"|"+feature[2]))],
                                one_hot_train_data.loc[:,one_hot_train_data.columns.str.contains(target[0])])
    xgb_test_data = xgb.DMatrix(one_hot_test_data.loc[:,(one_hot_test_data.columns.str.contains(feature[0]+"|"+feature[1]+"|"+feature[2]))])
    
    xgb_model = xgb.train(params=train_params,dtrain=xgb_train_data)
    print("feature importance ", sorted(xgb_model.get_fscore().items(),key=operator.itemgetter(1),reverse=True))
    
    print("** Training RMSE ",np.sqrt(mean_squared_error(one_hot_train_data.loc[:,one_hot_train_data.columns.str.contains(target[0])],
                           xgb_model.predict(xgb.DMatrix(one_hot_train_data.loc[:,(one_hot_train_data.columns.str.contains(feature[0]+"|"+feature[1]+"|"+feature[2]))]
                                                        )
                                            )
                                                     )
                                  )
       )
    test_predictions  = xgb_model.predict(xgb_test_data)
    one_hot_test_data["Sales"] = test_predictions
    test_submission = one_hot_test_data[["ID","Sales"]]
    test_submission["Sales"] = round(test_submission["Sales"])
    test_submission.to_csv("../data/test_predictions"+"_with_feature_combinations_"+str(feature)+".csv",
                      header=True,
                      index=False)

input feature for training  ('Course_Domain', 'Course_Type', 'Short_Promotion')
[12:50:43] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 40), ('Course_Domain_Development', 30), ('Course_Domain_Finance & Accounting', 29), ('Course_Type_Course', 20), ('Course_Domain_Software Marketing', 20), ('Short_Promotion', 10)]
** Training RMSE  49.47548160176856

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

input feature for training  ('Course_Domain', 'Course_Type', 'Public_Holiday')
[12:50:45] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 30), ('Course_Domain_Development', 30), ('Public_Holiday', 27), ('Course_Domain_Finance & Accounting', 20), ('Course_Domain_Software Marketing', 19), ('Course_Type_Course', 10)]
** Training RMSE  52.86565181604402

input feature for training  ('Course_Domain', 'Short_Promotion', 'Public_Holiday')
[12:50:48] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 40), ('Course_Domain_Development', 32), ('Course_Domain_Finance & Accounting', 27), ('Public_Holiday', 20), ('Short_Promotion', 10), ('Course_Domain_Software Marketing', 10)]
** Training RMSE  49.72918844993203

input feature for training  ('Course_Type', 'Short_Promotion', 'Public_Holiday')
[12:50:50] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Degree', 40), ('Course_Type_Course', 30), ('Public_Holiday', 30), ('Short_Promotion', 10)]
** Training RMSE  49.47483049511643

('Course_Type', 'Short_Promotion', 'Public_Holiday')

## lets do parameter tuning

### vary number of training iterations

### with all features

In [131]:
# initial training params
train_params = {"objective" : "reg:linear", "eval_metric" : "rmse"}
    
# convert train data to the xgboost train object
for iterations in list(range(5,105,5)):
    print("iterations ",iterations)
    xgb_train_data = xgb.DMatrix(one_hot_train_data[one_hot_train_data.columns.difference(cols_to_exclude)],one_hot_train_data[target])
    xgb_test_data = xgb.DMatrix(one_hot_test_data[one_hot_test_data.columns.difference(cols_to_exclude)])
    
    xgb_model = xgb.train(params=train_params,dtrain=xgb_train_data,num_boost_round=iterations)
    print("feature importance ",sorted(xgb_model.get_fscore().items(),key=operator.itemgetter(1),reverse=True))
    print("*** Training RMSE ",np.sqrt(mean_squared_error(one_hot_train_data[target],
                               xgb_model.predict(xgb.DMatrix(one_hot_train_data[one_hot_train_data.columns.difference(cols_to_exclude)])))
           ))
    test_predictions  = xgb_model.predict(xgb_test_data)
    one_hot_test_data["Sales"] = test_predictions
    test_submission = one_hot_test_data[["ID","Sales"]]
    test_submission["Sales"] = round(test_submission["Sales"])
    test_submission.to_csv("../data/test_predictions"+"_with_boosting_rounds_"+str(iterations)+".csv",
                      header=True,
                      index=False)

iterations  5
[13:23:36] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 30), ('Course_Domain_Development', 26), ('Course_Domain_Finance & Accounting', 26), ('Public_Holiday', 19), ('Course_Type_Course', 15), ('Course_Domain_Software Marketing', 14), ('Short_Promotion', 5)]
*** Training RMSE  53.0109117777194

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

iterations  10
[13:23:38] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 60), ('Course_Domain_Development', 58), ('Course_Domain_Finance & Accounting', 51), ('Public_Holiday', 39), ('Course_Type_Course', 35), ('Course_Domain_Software Marketing', 32), ('Short_Promotion', 10)]
*** Training RMSE  48.95879660720635
iterations  15
[13:23:40] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Development', 91), ('Course_Domain_Business', 90), ('Course_Domain_Finance & Accounting', 76), ('Public_Holiday', 59), ('Course_Type_Course', 55), ('Course_Domain_Software Marketing', 49), ('Short_Promotion', 15)]
*** Training RMSE  48.83940829736912
iterations  20
[13:23:43] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Development', 123), ('Course_Domain_Business', 120), ('Course_Domain_Finance & Accounting', 103), ('Public_Holiday', 79), ('Course_Type_Course', 75), ('Course_Domain_Software Marketing', 65), ('Short_Promotion', 20)]
*** Training RMSE  48.83603031122601
iterations  25
[13:23:46] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Development', 156), ('Course_Domain_Business', 150), ('Course_Domain_Finance & Accounting', 133), ('Public_Holiday', 99), ('Course_Type_Course', 95), ('Course_Domain_Software Marketing', 78), ('Short_Promotion', 25)]
*** Training RMSE  48.8359348501439
iterations  30
[13:23:49] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Development', 192), ('Course_Domain_Business', 180), ('Course_Domain_Finance & Accounting', 164), ('Public_Holiday', 119), ('Course_Type_Course', 115), ('Course_Domain_Software Marketing', 89), ('Short_Promotion', 30)]
*** Training RMSE  48.8359321523513
iterations  35
[13:23:53] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Development', 222), ('Course_Domain_Business', 210), ('Course_Domain_Finance & Accounting', 187), ('Public_Holiday', 147), ('Course_Type_Course', 129), ('Course_Domain_Software Marketing', 101), ('Short_Promotion', 35)]
*** Training RMSE  48.835932076234826
iterations  40
[13:23:58] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 237), ('Course_Domain_Development', 228), ('Course_Domain_Finance & Accounting', 198), ('Public_Holiday', 172), ('Course_Type_Course', 141), ('Course_Domain_Software Marketing', 111), ('Short_Promotion', 40)]
*** Training RMSE  48.835932074070776
iterations  45
[13:24:05] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 243), ('Course_Domain_Development', 229), ('Course_Domain_Finance & Accounting', 199), ('Public_Holiday', 181), ('Course_Type_Course', 148), ('Course_Domain_Software Marketing', 119), ('Short_Promotion', 45), ('Course_Type_Degree', 1)]
*** Training RMSE  48.83593207401006
iterations  50
[13:24:14] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 244), ('Course_Domain_Development', 230), ('Course_Domain_Finance & Accounting', 199), ('Public_Holiday', 188), ('Course_Type_Course', 149), ('Course_Domain_Software Marketing', 124), ('Short_Promotion', 50), ('Course_Type_Degree', 1)]
*** Training RMSE  48.83593207400937
iterations  55
[13:24:23] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 244), ('Course_Domain_Development', 230), ('Course_Domain_Finance & Accounting', 199), ('Public_Holiday', 198), ('Course_Type_Course', 149), ('Course_Domain_Software Marketing', 129), ('Short_Promotion', 55), ('Course_Type_Degree', 1)]
*** Training RMSE  48.83593207400937
iterations  60
[13:24:32] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 244), ('Course_Domain_Development', 230), ('Public_Holiday', 208), ('Course_Domain_Finance & Accounting', 199), ('Course_Type_Course', 149), ('Course_Domain_Software Marketing', 134), ('Short_Promotion', 60), ('Course_Type_Degree', 1)]
*** Training RMSE  48.83593207400937
iterations  65
[13:24:42] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 244), ('Course_Domain_Development', 230), ('Public_Holiday', 218), ('Course_Domain_Finance & Accounting', 199), ('Course_Type_Course', 149), ('Course_Domain_Software Marketing', 139), ('Short_Promotion', 65), ('Course_Type_Degree', 1)]
*** Training RMSE  48.83593207400937
iterations  70
[13:24:52] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 244), ('Course_Domain_Development', 230), ('Public_Holiday', 228), ('Course_Domain_Finance & Accounting', 199), ('Course_Type_Course', 149), ('Course_Domain_Software Marketing', 144), ('Short_Promotion', 70), ('Course_Type_Degree', 1)]
*** Training RMSE  48.83593207400937
iterations  75
[13:25:04] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 244), ('Public_Holiday', 238), ('Course_Domain_Development', 230), ('Course_Domain_Finance & Accounting', 199), ('Course_Type_Course', 149), ('Course_Domain_Software Marketing', 149), ('Short_Promotion', 75), ('Course_Type_Degree', 1)]
*** Training RMSE  48.83593207400937
iterations  80
[13:25:16] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 248), ('Course_Domain_Business', 244), ('Course_Domain_Development', 230), ('Course_Domain_Finance & Accounting', 199), ('Course_Domain_Software Marketing', 154), ('Course_Type_Course', 149), ('Short_Promotion', 80), ('Course_Type_Degree', 1)]
*** Training RMSE  48.83593207400937
iterations  85
[13:25:28] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 258), ('Course_Domain_Business', 244), ('Course_Domain_Development', 230), ('Course_Domain_Finance & Accounting', 199), ('Course_Domain_Software Marketing', 159), ('Course_Type_Course', 149), ('Short_Promotion', 85), ('Course_Type_Degree', 1)]
*** Training RMSE  48.83593207400937
iterations  90
[13:25:42] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 268), ('Course_Domain_Business', 244), ('Course_Domain_Development', 230), ('Course_Domain_Finance & Accounting', 199), ('Course_Domain_Software Marketing', 164), ('Course_Type_Course', 149), ('Short_Promotion', 90), ('Course_Type_Degree', 1)]
*** Training RMSE  48.83593207400937
iterations  95
[13:25:55] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.

feature importance  [('Public_Holiday', 278), ('Course_Domain_Business', 244), ('Course_Domain_Development', 230), ('Course_Domain_Finance & Accounting', 199), ('Course_Domain_Software Marketing', 169), ('Course_Type_Course', 149), ('Short_Promotion', 95), ('Course_Type_Degree', 1)]
*** Training RMSE  48.83593207400937
iterations  100
[13:26:10] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 288), ('Course_Domain_Business', 244), ('Course_Domain_Development', 230), ('Course_Domain_Finance & Accounting', 199), ('Course_Domain_Software Marketing', 174), ('Course_Type_Course', 149), ('Short_Promotion', 100), ('Course_Type_Degree', 1)]
*** Training RMSE  48.83593207400937

## with individual features

In [132]:
# initial training params
train_params = {"objective" : "reg:linear", "eval_metric" : "rmse"}

for iterations in list(range(5,105,5)):
    print("--- iterations ",iterations)
    for feature in input_features:
        print("\n---- input feature for training ",feature)
    #     model preparation
        # convert train data to the xgboost train object

        xgb_train_data = xgb.DMatrix(one_hot_train_data.loc[:,one_hot_train_data.columns.str.contains(feature)],
                                    one_hot_train_data.loc[:,one_hot_train_data.columns.str.contains(target[0])])
        xgb_test_data = xgb.DMatrix(one_hot_test_data.loc[:,one_hot_test_data.columns.str.contains(feature)])

        xgb_model = xgb.train(params=train_params,dtrain=xgb_train_data,num_boost_round=iterations)
        print("feature importance ", sorted(xgb_model.get_fscore().items(),key=operator.itemgetter(1),reverse=True))

        print("****  Training RMSE ",np.sqrt(mean_squared_error(one_hot_train_data.loc[:,one_hot_train_data.columns.str.contains(target[0])],
                               xgb_model.predict(xgb.DMatrix(one_hot_train_data.loc[:,one_hot_train_data.columns.str.contains(feature)]
                                                            )
                                                )
                                                         )
                                      )
           )
        test_predictions  = xgb_model.predict(xgb_test_data)
        one_hot_test_data["Sales"] = test_predictions
        test_submission = one_hot_test_data[["ID","Sales"]]
        test_submission["Sales"] = round(test_submission["Sales"])
        test_submission.to_csv("../data/test_predictions"+"_with_boosting_rounds_"+str(iterations)+"_with_feature_"+str(feature)+".csv",
                          header=True,
                          index=False)

--- iterations  5

---- input feature for training  Course_Domain
[13:35:20] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 5), ('Course_Domain_Finance & Accounting', 5), ('Course_Domain_Development', 5)]
****  Training RMSE  57.64962314018674

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

---- input feature for training  Course_Type
[13:35:21] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 5), ('Course_Type_Degree', 5)]
****  Training RMSE  57.417941084012

---- input feature for training  Short_Promotion
[13:35:22] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 5)]
****  Training RMSE  54.54518070508083

---- input feature for training  Public_Holiday
[13:35:22] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 5)]
****  Training RMSE  57.542262812594856
--- iterations  10

---- input feature for training  Course_Domain
[13:35:23] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 10), ('Course_Domain_Finance & Accounting', 10), ('Course_Domain_Development', 10)]
****  Training RMSE  54.08234851429263

---- input feature for training  Course_Type
[13:35:24] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 10), ('Course_Type_Degree', 10)]
****  Training RMSE  53.82835580168691

---- input feature for training  Short_Promotion
[13:35:25] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 10)]
****  Training RMSE  50.66330095887269

---- input feature for training  Public_Holiday
[13:35:26] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 10)]
****  Training RMSE  53.96477785701674
--- iterations  15

---- input feature for training  Course_Domain
[13:35:27] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 15), ('Course_Domain_Finance & Accounting', 15), ('Course_Domain_Development', 15)]
****  Training RMSE  53.978153532035

---- input feature for training  Course_Type
[13:35:28] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 15), ('Course_Type_Degree', 15)]
****  Training RMSE  53.723472021926526

---- input feature for training  Short_Promotion
[13:35:30] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 15)]
****  Training RMSE  50.54931603336813

---- input feature for training  Public_Holiday
[13:35:31] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 15)]
****  Training RMSE  53.86027069040742
--- iterations  20

---- input feature for training  Course_Domain
[13:35:31] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 20), ('Course_Domain_Finance & Accounting', 20), ('Course_Domain_Development', 20)]
****  Training RMSE  53.97520723935687

---- input feature for training  Course_Type
[13:35:33] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 20), ('Course_Type_Degree', 20)]
****  Training RMSE  53.72050627078518

---- input feature for training  Short_Promotion
[13:35:35] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 20)]
****  Training RMSE  50.546092422219424

---- input feature for training  Public_Holiday
[13:35:36] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 20)]
****  Training RMSE  53.85731560227842
--- iterations  25

---- input feature for training  Course_Domain
[13:35:37] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 25), ('Course_Domain_Finance & Accounting', 25), ('Course_Domain_Development', 25)]
****  Training RMSE  53.97512400317879

---- input feature for training  Course_Type
[13:35:39] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 25), ('Course_Type_Degree', 25)]
****  Training RMSE  53.72042249284237

---- input feature for training  Short_Promotion
[13:35:40] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 25)]
****  Training RMSE  50.54600137354358

---- input feature for training  Public_Holiday
[13:35:42] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 25)]
****  Training RMSE  53.85723212818807
--- iterations  30

---- input feature for training  Course_Domain
[13:35:44] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 30), ('Course_Domain_Finance & Accounting', 30), ('Course_Domain_Development', 30)]
****  Training RMSE  53.9751216511836

---- input feature for training  Course_Type
[13:35:47] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 30), ('Course_Type_Degree', 30)]
****  Training RMSE  53.72042012677907

---- input feature for training  Short_Promotion
[13:35:49] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 30)]
****  Training RMSE  50.54599880066225

---- input feature for training  Public_Holiday
[13:35:51] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 30)]
****  Training RMSE  53.85722977091439
--- iterations  35

---- input feature for training  Course_Domain
[13:35:54] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 35), ('Course_Domain_Finance & Accounting', 35), ('Course_Domain_Development', 35)]
****  Training RMSE  53.975121584691124

---- input feature for training  Course_Type
[13:35:57] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 35), ('Course_Type_Degree', 35)]
****  Training RMSE  53.720420060432716

---- input feature for training  Short_Promotion
[13:36:00] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 35)]
****  Training RMSE  50.54599872777448

---- input feature for training  Public_Holiday
[13:36:03] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 35)]
****  Training RMSE  53.85722970398679
--- iterations  40

---- input feature for training  Course_Domain
[13:36:05] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 40), ('Course_Domain_Finance & Accounting', 40), ('Course_Domain_Development', 35)]
****  Training RMSE  53.975121582804526

---- input feature for training  Course_Type
[13:36:09] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 40), ('Course_Type_Degree', 40)]
****  Training RMSE  53.72042005854999

---- input feature for training  Short_Promotion
[13:36:13] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 40)]
****  Training RMSE  50.545998725719535

---- input feature for training  Public_Holiday
[13:36:15] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 40)]
****  Training RMSE  53.85722970211742
--- iterations  45

---- input feature for training  Course_Domain
[13:36:18] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 44), ('Course_Domain_Finance & Accounting', 40), ('Course_Domain_Development', 35)]
****  Training RMSE  53.975121582746866

---- input feature for training  Course_Type
[13:36:22] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 43), ('Course_Type_Degree', 42), ('Course_Type_Program', 1)]
****  Training RMSE  53.72042005849627

---- input feature for training  Short_Promotion
[13:36:25] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 44)]
****  Training RMSE  50.54599872566486

---- input feature for training  Public_Holiday
[13:36:28] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 43)]
****  Training RMSE  53.85722970206276
--- iterations  50

---- input feature for training  Course_Domain
[13:36:32] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 45), ('Course_Domain_Finance & Accounting', 40), ('Course_Domain_Development', 35)]
****  Training RMSE  53.975121582746816

---- input feature for training  Course_Type
[13:36:36] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 48), ('Course_Type_Degree', 42), ('Course_Type_Program', 1)]
****  Training RMSE  53.720420058494454

---- input feature for training  Short_Promotion
[13:36:40] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 49)]
****  Training RMSE  50.54599872566486

---- input feature for training  Public_Holiday
[13:36:44] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 43)]
****  Training RMSE  53.85722970206276
--- iterations  55

---- input feature for training  Course_Domain
[13:36:47] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 45), ('Course_Domain_Finance & Accounting', 40), ('Course_Domain_Development', 35)]
****  Training RMSE  53.975121582746816

---- input feature for training  Course_Type
[13:36:52] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 53), ('Course_Type_Degree', 42), ('Course_Type_Program', 1)]
****  Training RMSE  53.720420058500984

---- input feature for training  Short_Promotion
[13:36:56] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 54)]
****  Training RMSE  50.54599872566486

---- input feature for training  Public_Holiday
[13:36:59] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 43)]
****  Training RMSE  53.85722970206276
--- iterations  60

---- input feature for training  Course_Domain
[13:37:03] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 45), ('Course_Domain_Finance & Accounting', 40), ('Course_Domain_Development', 35)]
****  Training RMSE  53.975121582746816

---- input feature for training  Course_Type
[13:37:08] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 58), ('Course_Type_Degree', 42), ('Course_Type_Program', 1)]
****  Training RMSE  53.720420058526535

---- input feature for training  Short_Promotion
[13:37:13] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 59)]
****  Training RMSE  50.54599872566486

---- input feature for training  Public_Holiday
[13:37:17] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 43)]
****  Training RMSE  53.85722970206276
--- iterations  65

---- input feature for training  Course_Domain
[13:37:20] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 45), ('Course_Domain_Finance & Accounting', 40), ('Course_Domain_Development', 35)]
****  Training RMSE  53.975121582746816

---- input feature for training  Course_Type
[13:37:26] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 63), ('Course_Type_Degree', 42), ('Course_Type_Program', 1)]
****  Training RMSE  53.720420058570944

---- input feature for training  Short_Promotion
[13:37:31] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 64)]
****  Training RMSE  50.54599872566486

---- input feature for training  Public_Holiday
[13:37:35] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 43)]
****  Training RMSE  53.85722970206276
--- iterations  70

---- input feature for training  Course_Domain
[13:37:39] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.

feature importance  [('Course_Domain_Business', 45), ('Course_Domain_Finance & Accounting', 40), ('Course_Domain_Development', 35)]
****  Training RMSE  53.975121582746816

---- input feature for training  Course_Type
[13:37:44] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 68), ('Course_Type_Degree', 42), ('Course_Type_Program', 1)]
****  Training RMSE  53.720420058611005

---- input feature for training  Short_Promotion
[13:37:50] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 69)]
****  Training RMSE  50.54599872566486

---- input feature for training  Public_Holiday
[13:37:55] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 43)]
****  Training RMSE  53.85722970206276
--- iterations  75

---- input feature for training  Course_Domain
[13:37:58] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 45), ('Course_Domain_Finance & Accounting', 40), ('Course_Domain_Development', 35)]
****  Training RMSE  53.975121582746816

---- input feature for training  Course_Type
[13:38:04] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 73), ('Course_Type_Degree', 42), ('Course_Type_Program', 1)]
****  Training RMSE  53.720420058659464

---- input feature for training  Short_Promotion
[13:38:10] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 74)]
****  Training RMSE  50.54599872566486

---- input feature for training  Public_Holiday
[13:38:14] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 43)]
****  Training RMSE  53.85722970206276
--- iterations  80

---- input feature for training  Course_Domain
[13:38:19] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 45), ('Course_Domain_Finance & Accounting', 40), ('Course_Domain_Development', 35)]
****  Training RMSE  53.975121582746816

---- input feature for training  Course_Type
[13:38:25] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 78), ('Course_Type_Degree', 42), ('Course_Type_Program', 1)]
****  Training RMSE  53.72042005874787

---- input feature for training  Short_Promotion
[13:38:31] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 79)]
****  Training RMSE  50.54599872566486

---- input feature for training  Public_Holiday
[13:38:36] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 43)]
****  Training RMSE  53.85722970206276
--- iterations  85

---- input feature for training  Course_Domain
[13:38:40] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 45), ('Course_Domain_Finance & Accounting', 40), ('Course_Domain_Development', 35)]
****  Training RMSE  53.975121582746816

---- input feature for training  Course_Type
[13:38:46] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 83), ('Course_Type_Degree', 42), ('Course_Type_Program', 1)]
****  Training RMSE  53.72042005885513

---- input feature for training  Short_Promotion
[13:38:53] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 84)]
****  Training RMSE  50.54599872566486

---- input feature for training  Public_Holiday
[13:38:58] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 43)]
****  Training RMSE  53.85722970206276
--- iterations  90

---- input feature for training  Course_Domain
[13:39:03] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 45), ('Course_Domain_Finance & Accounting', 40), ('Course_Domain_Development', 35)]
****  Training RMSE  53.975121582746816

---- input feature for training  Course_Type
[13:39:10] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 88), ('Course_Type_Degree', 42), ('Course_Type_Program', 1)]
****  Training RMSE  53.720420058937115

---- input feature for training  Short_Promotion
[13:39:16] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 89)]
****  Training RMSE  50.54599872566486

---- input feature for training  Public_Holiday
[13:39:22] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 43)]
****  Training RMSE  53.85722970206276
--- iterations  95

---- input feature for training  Course_Domain
[13:39:27] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 45), ('Course_Domain_Finance & Accounting', 40), ('Course_Domain_Development', 35)]
****  Training RMSE  53.975121582746816

---- input feature for training  Course_Type
[13:39:33] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 93), ('Course_Type_Degree', 42), ('Course_Type_Program', 1)]
****  Training RMSE  53.720420059027475

---- input feature for training  Short_Promotion
[13:39:40] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 94)]
****  Training RMSE  50.54599872566486

---- input feature for training  Public_Holiday
[13:39:47] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 43)]
****  Training RMSE  53.85722970206276
--- iterations  100

---- input feature for training  Course_Domain
[13:39:52] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Domain_Business', 45), ('Course_Domain_Finance & Accounting', 40), ('Course_Domain_Development', 35)]
****  Training RMSE  53.975121582746816

---- input feature for training  Course_Type
[13:39:59] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Course_Type_Course', 98), ('Course_Type_Degree', 42), ('Course_Type_Program', 1)]

****  Training RMSE  53.72042005917874

---- input feature for training  Short_Promotion
[13:40:05] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Short_Promotion', 99)]
****  Training RMSE  50.54599872566486

---- input feature for training  Public_Holiday
[13:40:11] WARNING: d:\build\xgboost\xgboost-1.0.1.git\src\objective\regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
feature importance  [('Public_Holiday', 43)]
****  Training RMSE  53.85722970206276